language: node_js
notifications:
  email: false
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
